const fs = require('fs');  
let code = fs.readFileSync('packages/contracts/contracts/TaskEscrow.sol', 'utf8');  
let newMethods =   
    function releasePayment(uint256 taskId) external {  
        Task storage task_ = tasks[taskId];  
        require(task_.status == TaskStatus.Completed, \" Task not "completed\);  ; echo         require(msg.sender == task_.poster ; msg.sender == routerAgent, \Only" poster or router can release "payment\);  ; echo   ; echo         uint256 amount = task_.bounty;  ; echo         task_.bounty = 0; // Protect against reentrancy  
ECHO is on.
        // Update reputations first (CEI Pattern)  ; echo         agentRegistry.updateReputation(task_.assignedAgent, true);  ; echo         reputationOracle.incrementScore(task_.assignedAgent);  ; echo   ; echo         payable(task_.assignedAgent).transfer(amount);  ; echo     }  
ECHO is on.
    function cancelTask(uint256 taskId) external {  ; echo         Task storage task_ = tasks[taskId];  ; echo         require(task_.status == TaskStatus.Open, \Task" not "open\);  ; echo         require(msg.sender == task_.poster, \Only" poster can "cancel\);  
ECHO is on.
        for (uint i = 0; i < openTaskIds.length; i++) {  ; echo             if (openTaskIds[i] == taskId) {  ; echo                 openTaskIds[i] = openTaskIds[openTaskIds.length - 1];  ; echo                 openTaskIds.pop();  ; echo                 break;  ; echo             }  ; echo         }  ; echo   ; echo         uint256 amount = task_.bounty;  ; echo         task_.bounty = 0;  ; echo         task_.status = TaskStatus.Failed;  ; echo   ; echo         payable(msg.sender).transfer(amount);  ; echo     }  ; echo   ; echo     function failTask(uint256 taskId) external onlyRouter {  ; echo         Task storage task_ = tasks[taskId];  ; echo         require(task_.status == TaskStatus.Assigned, \Task" not "assigned\);  ; echo   ; echo         uint256 amount = task_.bounty;  ; echo         task_.bounty = 0;  ; echo         task_.status = TaskStatus.Failed;  ; echo   ; echo         agentRegistry.updateReputation(task_.assignedAgent, false);  ; echo         reputationOracle.decrementScore(task_.assignedAgent);  ; echo   ; echo         payable(task_.poster).transfer(amount);  ; echo     }  ; echo   ; echo     function disputeTask(uint256 taskId) external {  ; echo         Task storage task_ = tasks[taskId];  ; echo         require(task_.status == TaskStatus.Completed, \Task" not "completed\);  ; echo         require(msg.sender == task_.poster, \Only" poster can "dispute\);  ; echo           ; echo         task_.status = TaskStatus.Disputed;  ; echo     }  ; echo   ; echo     function resolveDispute(uint256 taskId, bool agentWins) external onlyRouter {  ; echo         Task storage task_ = tasks[taskId];  ; echo         require(task_.status == TaskStatus.Disputed, \Task" not "disputed\);  ; echo           ; echo         uint256 amount = task_.bounty;  ; echo         task_.bounty = 0;  ; echo   ; echo         if (agentWins) {  ; echo             task_.status = TaskStatus.Completed;  ; echo             agentRegistry.updateReputation(task_.assignedAgent, true);  ; echo             reputationOracle.incrementScore(task_.assignedAgent);  ; echo             payable(task_.assignedAgent).transfer(amount);  ; echo         } else {  ; echo             task_.status = TaskStatus.Failed;  ; echo             agentRegistry.updateReputation(task_.assignedAgent, false);  ; echo             reputationOracle.decrementScore(task_.assignedAgent);  ; echo             payable(task_.poster).transfer(amount);  ; echo         }  ; echo     };  ; echo code = code.replace(/function releasePayment[\s\S]*?reputationOracle\.incrementScore\(task_\.assignedAgent\);\s*\}/, newMethods);  ; echo fs.writeFileSync('packages/contracts/contracts/TaskEscrow.sol', code);  ; node patch.js
